# Generated by Django 4.2.3 on 2025-01-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_skills_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
